query V3TransactionsQuery($fromHead: Boolean, $first: Int, $skip: Int, $where: V3TransactionWhere) {
  v3transactions(fromHead: $fromHead, first: $first, skip: $skip, where: $where) {
      id
      chainId
      poolAddress
      amount0
      amount1
      archiveToken0UsdPrice
      archiveToken1UsdPrice
      txHash
      txTimestamp
      blockNumber
  }
}
