query V3SwapsQuery($fromHead: Boolean, $first: Int, $skip: Int, $where: V3SwapWhere) {
  v3swaps(fromHead: $fromHead, first: $first, skip: $skip, where: $where) {
      id
      chainId
      poolAddress
      amount0
      amount1
      archiveToken0UsdPrice
      archiveToken1UsdPrice
      txHash
      txTimestamp
      blockNumber
  }
}
